spring:
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: ecommerce-streams
      properties:
        commit.interval.ms: 1000
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde